spring:
  datasource:
    url: jdbc:${MYSQLDBURL0:mysql://root:123456@localhost:3306/sbhrm}?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: ${PORT:8081}
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG