spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sbhrm?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8081
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG